language: cpp

_shared_job: &gcc-8
  - os: linux
    addons:
      apt:
        sources:
          - *default_sources
          - ubuntu-toolchain-r-test
        packages:
          - *default_packages
          - g++-8
    env:
      - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

_shared_job: &clang-10
  - os: linux
    addons:
      apt:
        sources:
          - *default_sources
          - llvm-toolchain-trusty-5.0
        packages:
          - *default_packages
          - clang-10
    env:
      - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"

_shared_job: &percona-5.7
  - os: linux
    before_install:
      - sudo apt-get install -y gnupg2
      - wget https://repo.percona.com/apt/percona-release_latest.$(lsb_release -sc)_all.deb
      - sudo dpkg -i percona-release_latest.$(lsb_release -sc)_all.deb
      - sudo apt-get update
      - sudo apt-get install percona-server-server-5.7 percona-server-client-5.7

matrix:
  include:
    # MySQL 5.7 is installed by default on Ubuntu Bionic (18.04)
    - name: Ubuntu 18.04 (Bionic), GCC 8, MySQL 5.7
      dist: bionic
      services:
        - mysql
      <<: *gcc-8
    - name: Ubuntu 18.04 (Bionic), Clang 10, MySQL 5.7
      dist: bionic
      services:
        - mysql
      <<: *clang-10

    # Percona 5.7
    - name: Ubuntu 18.04 (Bionic), GCC 8, MySQL 5.7
      dist: bionic
      <<: *percona-5.7
      <<: *gcc-8
    - name: Ubuntu 18.04 (Bionic), Clang 10, MySQL 5.7
      dist: bionic
      <<: *percona-5.7
      <<: *clang-10

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
    - DEBIAN_FRONTEND=noninteractive sudo -E apt update -y
    - DEBIAN_FRONTEND=noninteractive sudo -E apt install -y libboost-all-dev
    - sudo cp $TRAVIS_BUILD_DIR/test/data/travis.cnf /etc/mysql/conf.d/
    - sudo service mysql restart
    - mysql -u root -e "CREATE USER tarantool IDENTIFIED BY 'tarantool';"
    - mysql -u root -e "GRANT ALL ON *.* TO tarantool;"
    - mysql -u root -e "CREATE USER 'tarantool'@'localhost' IDENTIFIED BY 'tarantool';"
    - mysql -u root -e "GRANT ALL ON *.* TO tarantool@localhost;"
    - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;"
    - mysql -u root -e "GRANT SELECT ON *.* TO 'tarantool'@'localhost';"
    - mysql -u root -e "GRANT REPLICATION CLIENT ON *.* TO tarantool@localhost;" || true
    - mysql -u root -e "GRANT REPLICATION SLAVE ON *.* TO tarantool@localhost;" || true
    - mysql -u root -e "FLUSH PRIVILEGES;"
    - mysql -e "CREATE DATABASE IF NOT EXISTS tarantool_mysql_test;"
    - mysql -e "SHOW DATABASES;"
    - mysql -e "SHOW VARIABLES LIKE '%bin%';"
    - mysql -e "SHOW BINARY LOGS;"
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DWITH_TESTING=ON .. 

script:
    - make
    - cd .. && ./build/test/unit_test --list_content && ./build/test/unit_test --run_test=*test_HelloWorld*,*test_Gtid*
    - test/run.sh
